# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0005_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
